# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.9.0
maven_group=semmiedev
archives_base_name=disc_jockey
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.155.2+26.2

#Fix tls problem
systemProp.jdk.tls.client.protocols=TLSv1.2,TLSv1.3
systemProp.https.protocols=TLSv1.2,TLSv1.3

org.gradle.jvmargs=-Dfile.encoding=UTF-8